feat: Introduce a ComponentBasedAlterationEffect
Terasology/AlterationEffects pull request #15
Opened 2020-07-12 14:34 UTC by skaldarnar

Extracted from #14

This is a common base class for alteration effects based on a single component. It only requires implementations of component _upsert_ and _update_ to fully define an effect (in addition to the component class and the general effect id). _Removing_ the component can also be customized.

The implementation is extracted from WalkSpeedAlterationEffect and can be found in other effect classes such as SwimSpeedAlterationEffect or StunEffect.

- [ ] add proper JavaDoc to new classes

2020-07-12 16:01 UTC, Cervator reviewed
Huh, this is somehow the first time I've ever encountered "upsert" as a term - after Googling it and understanding it is a mix of "update" + "insert" it makes perfect sense, and I can think of at least one other place we could use it as well (there's some spot with the ES and components where you want to either add or save or update a component or something - I can't find the exact spot right now). Might be worth explaining the term in the javadoc tho?

As for the code I think I get where the desire from this approach comes from and we again have hit that from time to time. While old habits speak against code in components I could see how it might fit in. If this is even truly meant to be used as a component anyway - it also kinda looks like a system (uses the delay manager).

If it _is_ meant to be used as a regular component it might also need a no-arg constructor, or it'll fail to serialize somewhere IIRC?

I don't remember much about it, but I think the equipment-applied effects also had some sort of elaborate system assigned to it to better deal with arbitrary effects. You might have already seen that, or it may be unrelated, but I thought I'd mention it.

Very curious to see where this goes and if maybe it could be a new pattern allowing for grouped components in some sense 👍

2020-07-12 16:01 UTC, Cervator commented on src/main/java/org/terasology/alterationEffects/EffectContext.java
> +public class EffectContext {
Would a different term than "Context" be an idea here, to avoid any term overlap with the `Context` class?

2020-07-12 16:44 UTC, skaldarnar commented
@Cervator We've already got `update` and `upsert` for components with extensive JavaDoc :wink: 

- https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/entitySystem/MutableComponentContainer.java#L114
- https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/entitySystem/MutableComponentContainer.java#L159

2020-07-12 16:52 UTC, skaldarnar commented on src/main/java/org/terasology/alterationEffects/EffectContext.java
> +public class EffectContext {
I'm open for suggestions :sweat_smile: naming is hard :confused:

2020-07-12 16:52 UTC, Cervator commented
Ooohhh. Cool. And sneaky. Totally missed that PR. Carry on then 👍

2020-07-12 16:55 UTC, Cervator commented on src/main/java/org/terasology/alterationEffects/EffectContext.java
> +public class EffectContext {
Agreed. We could just be boring and call it `EffectWrapper` or something. It almost looks like an event or even an action? `EffectAction` ? Hmm 🤔

2020-07-12 21:19 UTC, skaldarnar commented on src/main/java/org/terasology/alterationEffects/EffectContext.java
> +public class EffectContext {
No, it's not an action - it is just a container for the arguments to `applyEffect`. I've added JavaDoc explaining this class in detail.

For this PR, I'd like to keep the name as it is in hope that I don't have to touch all the extracted PRs per package with a renaming. I'd be happy to rename once those are merged, though (IntelliJ refactoring ftw). 

What about `EffectInfo` or `EffectRequest` or `EffectInitializer`? Although _initializer_ sounds too active again - this is just a data container in the end...

2020-07-14 21:10 UTC, skaldarnar reviewed
This is up for review now.

As I've stated somehwere in the docstrings I believe this to be a temporary solution™️ before we switch to alteration effects fully backed and integrated into the ECS.

2020-07-14 21:10 UTC, skaldarnar commented on src/main/java/org/terasology/alterationEffects/ComponentBasedAlterationEffect.java
> +     * </ul>
This part is contributed by @jdrueckert - I take no credits for this (that's what goes beyon my knowledge, I cannot wrap around my head around this conditional construct 🙈 )

2020-07-17 19:37 UTC, skaldarnar commented on src/main/java/org/terasology/alterationEffects/ComponentBasedAlterationEffect.java
> +     * the correct state is handled by {@link #updateComponent(OnEffectModifyEvent, Component, EffectContext)}.
Hm, I'm no longer so sure about this statement 🤔 well, I think it still holds, but it takes away one of the major points of the initial idea of alteration effects - avoid writing a system/event handler to apply an alteration effect... still, the current behavior seems buggy, so I'd like to keep that as a reminder for consumers.

2020-07-17 20:23 UTC, jdrueckert requested changes

2020-07-17 20:23 UTC, jdrueckert commented on src/main/java/org/terasology/alterationEffects/ComponentBasedAlterationEffect.java
> +     * Upsert denotes the the operation to either insert (i.e., create) or update the backing component. If the
```suggestion
     * Upsert denotes the operation to either insert (i.e., create) or update the backing component. If the
```

2020-07-17 20:23 UTC, jdrueckert commented on src/main/java/org/terasology/alterationEffects/ComponentBasedAlterationEffect.java
> +     * backing component is present on an entity. This should be the main method to update the entities state. If the
```suggestion
     * backing component is present on an entity. This should be the main method to update the entity's state. If the
```

2020-07-17 20:23 UTC, jdrueckert commented on src/main/java/org/terasology/alterationEffects/ComponentBasedAlterationEffect.java
> +     * @param event event holding modifications to duration or magnitude by other systems
```suggestion
     * @param event the event holding modifications to duration or magnitude by other systems
```

2020-07-17 20:23 UTC, jdrueckert commented on src/main/java/org/terasology/alterationEffects/EffectContext.java
> +public class EffectContext {
looks like you agreed on one of `EffectWrapper`, `EffectInfo` or `EffectRequest`... so I guess this still needs the associate adjustments?

2020-07-17 20:51 UTC, jdrueckert approved these changes

2020-07-17 20:51 UTC, jdrueckert commented on src/main/java/org/terasology/alterationEffects/EffectContext.java
> +public class EffectContext {
Only now saw the line about doing the renaming after the other PRs are merged.
As long as we don't forget to do so, I'm fine with merging this now.

2020-07-17 20:55 UTC, merged